# Start the project by loading the .env.dev file
#
# Development:
# `docker compose up -d --env-file .env.dev`
#
# Production:
# `docker compose up -d --env-file .env.prod`

services:
    nextjs:
        build:
            context: ./
            dockerfile: ${DOCKERFILE}
        container_name: nextjs
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=${NODE_ENV}
        restart: unless-stopped
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - nextjs-network

    mysql:
        image: mysql:9.3
        container_name: mysql
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - mysql-volume:/var/lib/mysql
        ports:
            - "${MYSQL_PORT}:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 60s
        networks:
            - nextjs-network

volumes:
    mysql-volume:
        name: data

networks:
    nextjs-network:
        driver: bridge
