# Start the project by loading the .env.dev file
#
# Development:
# `docker compose up -d --env-file .env.dev`
#
# Production:
# `docker compose up -d --env-file .env.prod`

services:
    nextjs:
        build:
            context: ./
            dockerfile: ./docker/${DOCKERFILE}
        container_name: nextjs
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=${NODE_ENV}
        restart: unless-stopped
        depends_on:
            mysql:
                condition: service_healthy
        volumes:
            - ./docker/certs:/app/certs:ro
        networks:
            - nextjs-network

    mysql:
        image: mysql:9.3
        container_name: mysql
        restart: unless-stopped
        command:
            [
                "mysqld",
                "--ssl-ca=/etc/mysql/certs/ca.pem",
                "--ssl-cert=/etc/mysql/certs/server-cert.pem",
                "--ssl-key=/etc/mysql/certs/server-key.pem",
            ]
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - mysql-volume:/var/lib/mysql
            - ./docker/certs:/etc/mysql/certs:ro
        ports:
            - "${MYSQL_PORT}:3306"
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "root",
                    "-proot",
                    "--ssl-ca=/etc/mysql/certs/ca.pem",
                ]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 60s
        networks:
            - nextjs-network

volumes:
    mysql-volume:
        name: data

networks:
    nextjs-network:
        driver: bridge
