name: CI

on:
    pull_request:
        branches: [main, test]
    push:
        branches: [main, test]

jobs:
    # check:
    #     name: Commit, lint and format check
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v4
    #         - name: Install nodejs
    #           uses: actions/setup-node@v4
    #           with:
    #               node-version: 23
    #         - name: Install pnpm
    #           uses: pnpm/action-setup@v3
    #           with:
    #               version: 10
    #         - name: Install dependencies
    #           run: pnpm install
    #         - name: Lint check
    #           run: pnpm lint
    #         - name: Format check
    #           run: pnpm format

    build:
        name: Build check
        runs-on: ubuntu-latest
        # needs: [check]
        services:
            mysql:
                image: mysql:9.3
                ports:
                    - "3306:3306"
                env:
                    MYSQL_DATABASE: eco_service_db
                    MYSQL_USER: eco_service_user
                    MYSQL_PASSWORD: eco_service_password
                    MYSQL_ROOT_PASSWORD: root
                options: >-
                  --health-cmd="mysqladmin ping -h localhost -u root -proot"
                  --health-interval=5s
                  --health-timeout=5s
                  --health-retries=10
                  --health-start-period=60s
        env:
            BASE_URL: "http://localhost:3000"
            DATABASE_URL: "mysql://eco_service_user:eco_service_password@127.0.0.1:3306/eco_service_db"
            BETTER_AUTH_SECRET: "session-encryption-key"
            PLUNK_API_KEY: "plunk-private-key"
            NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "pk_test_xxxxx"
            STRIPE_SECRET_KEY: "sk_test_pk_test_xxxxx"
            STRIPE_WEBHOOK_SECRET: "whsec_xxxxx"

        steps:
            - uses: actions/checkout@v4
            - name: Install nodejs
              uses: actions/setup-node@v4
              with:
                  node-version: 23
            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 10
            - name: Install dependencies
              run: pnpm install
            - name: Grant all privileges (global)
              run: mysql -h 127.0.0.1 -u root -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'eco_service_user'@'%'; FLUSH PRIVILEGES;"
            - name: Grant all privileges (db)
              run: mysql -h 127.0.0.1 -u root -proot -e "GRANT ALL PRIVILEGES ON eco_service_db.* TO 'eco_service_user'@'%'; FLUSH PRIVILEGES;"
            - name: Generate Prisma client
              run: pnpm prisma:generate
            - name: Deploy Prisma migrations
              run: pnpm prisma:deploy
            - name: Install fixtures
              run: pnpm fixtures:setup
            # - name: Run tests
            #   run: pnpm test:run
            - name: Build check
              run: pnpm run build
